// src/lang.js
// Language translations for LandingPage

const translations = {
  en: {
    clubName: 'Aalborg Cricket Club',
    welcome: 'Welcome to Aalborg Cricket Club',
    aboutTitle: 'About Our Club',
    aboutText: 'Founded with a vision to promote cricket excellence, Aalborg Cricket Club has been a cornerstone of the community for decades. We offer programs for players of all ages and skill levels, from juniors learning the basics to seasoned professionals.',
    newsTitle: 'Latest News',
    newsDesc: 'Stay updated with the latest happenings at our club',
    eventsTitle: 'Upcoming Events',
    eventsDesc: 'Join us for exciting cricket events and activities',
    contactTitle: 'Get in Touch',
    contactDesc: "Have questions? We'd love to hear from you!",
    contactInfo: 'Contact Information',
    followUs: 'Follow Us',
    adminPortal: 'Admin Portal',
    accessAdmin: 'Access Admin Portal',
    getInTouch: 'Get in Touch',
    excellence: 'Excellence',
    excellenceDesc: 'Committed to developing skills and achieving success on and off the field.',
    community: 'Community',
    communityDesc: 'Building lasting relationships and fostering a supportive environment.',
    achievement: 'Achievement',
    achievementDesc: 'Celebrating victories and recognizing the dedication of our members.',
    addressBoxes: [
      {
        icon: '🏏',
        heading: 'Ground',
        address: 'Dyrskueplads, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskueplads,+9200+Aalborg+SV,+Aalborg%2B/data=!4m5!4m4!1m0!1m2!1m1!1s0x464933a17f39d5a3:0x91351939e1b4eef0?sa=X&ved=2ahUKEwjPof6x9IPdAhXGJlAKHfT4CHQQ9RcwC3oECAoQEA',
      },
      {
        icon: '🅿️',
        heading: 'Parking',
        address: 'Hobrovej 437, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir/Hobrovej+437,+9200+Aalborg//@57.0066659,9.8791338,16z/data=!4m8!4m7!1m5!1m1!1s0x464933a2396ee279:0x17f161795534b053!2m2!1d9.8835219!2d57.006666!1m0',
      },
      {
        icon: '📬',
        heading: 'Post Address',
        address: 'H. C. Andersens Vej 20, 9000 Aalborg',
        link: null,
      },
      {
        icon: '🚻',
        heading: 'Changing Room & Cafeteria',
        address: 'Dyrskuevej 2, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskuevej+2,+9200+Aalborg/@57.0065879,9.8825229,16z/data=!4m8!4m7!1m0!1m5!1m1!1s0x464933a1976f7c2d:0xea5304c1daa65d8a!2m2!1d9.886911!2d57.006588',
      },
    ],
    phone: '📞 +45 12 34 56 78',
    email: '✉️ info@aalborgcricketclub.com',
    copyright: '© 2026 Aalborg Cricket Club. All rights reserved.',
    about: 'About',
    news: 'News',
    events: 'Events',
    contact: 'Contact',
    light: '☀️ Light',
    dark: '🌙 Dark',
    lang: 'Dansk',
    facebook: 'Facebook',
    instagram: 'Instagram',
    twitter: 'Twitter',
  },
  da: {
    clubName: 'Aalborg Cricket Klub',
    welcome: 'Velkommen til Aalborg Cricket Klub',
    aboutTitle: 'Om Klubben',
    aboutText: 'Aalborg Cricket Klub har i årtier været en hjørnesten i lokalsamfundet med fokus på cricket og fællesskab. Vi tilbyder programmer for alle aldre og niveauer, fra begyndere til erfarne spillere.',
    newsTitle: 'Seneste Nyt',
    newsDesc: 'Hold dig opdateret med de seneste begivenheder i klubben',
    eventsTitle: 'Kommende Begivenheder',
    eventsDesc: 'Deltag i spændende cricketarrangementer og aktiviteter',
    contactTitle: 'Kontakt Os',
    contactDesc: 'Har du spørgsmål? Vi hører gerne fra dig!',
    contactInfo: 'Kontaktinformation',
    followUs: 'Følg Os',
    adminPortal: 'Admin Portal',
    accessAdmin: 'Gå til Admin Portal',
    getInTouch: 'Kontakt',
    excellence: 'Fremragende',
    excellenceDesc: 'Vi arbejder målrettet på at udvikle færdigheder og opnå succes både på og udenfor banen.',
    community: 'Fællesskab',
    communityDesc: 'Vi bygger varige relationer og skaber et støttende miljø.',
    achievement: 'Præstation',
    achievementDesc: 'Vi fejrer sejre og anerkender medlemmernes engagement.',
    addressBoxes: [
      {
        icon: '🏏',
        heading: 'Bane',
        address: 'Dyrskueplads, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskueplads,+9200+Aalborg+SV,+Aalborg%2B/data=!4m5!4m4!1m0!1m2!1m1!1s0x464933a17f39d5a3:0x91351939e1b4eef0?sa=X&ved=2ahUKEwjPof6x9IPdAhXGJlAKHfT4CHQQ9RcwC3oECAoQEA',
      },
      {
        icon: '🅿️',
        heading: 'Parkering',
        address: 'Hobrovej 437, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir/Hobrovej+437,+9200+Aalborg//@57.0066659,9.8791338,16z/data=!4m8!4m7!1m5!1m1!1s0x464933a2396ee279:0x17f161795534b053!2m2!1d9.8835219!2d57.006666!1m0',
      },
      {
        icon: '📬',
        heading: 'Postadresse',
        address: 'H. C. Andersens Vej 20, 9000 Aalborg',
        link: null,
      },
      {
        icon: '🚻',
        heading: 'Omklædning & Cafeteria',
        address: 'Dyrskuevej 2, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskuevej+2,+9200+Aalborg/@57.0065879,9.8825229,16z/data=!4m8!4m7!1m0!1m5!1m1!1s0x464933a1976f7c2d:0xea5304c1daa65d8a!2m2!1d9.886911!2d57.006588',
      },
    ],
    phone: '📞 +45 12 34 56 78',
    email: '✉️ info@aalborgcricketclub.com',
    copyright: '© 2026 Aalborg Cricket Klub. Alle rettigheder forbeholdes.',
    about: 'Om',
    news: 'Nyt',
    events: 'Begivenheder',
    contact: 'Kontakt',
    light: '☀️ Lys',
    dark: '🌙 Mørk',
    lang: 'English',
    facebook: 'Facebook',
    instagram: 'Instagram',
    twitter: 'Twitter',
  },
};

export default translations;
