// src/lang.js
// Language translations for LandingPage

const translations = {
  en: {
    clubName: 'Aalborg Cricket Club',
    welcome: 'Welcome to Aalborg Cricket Club',
    aboutTitle: 'About Our Club',
    aboutHistoryTitle: 'Cricket History in Aalborg',
    aboutHistoryText: 'Cricket in Denmark has a long history. The most successful club over time is Svanholm CC, located in Brøndby. Aalborg is the second city on the championship list, with 17 Senior Danish Championships: Aab with 16 and Chang with 1.\n\nOfficial club cricket in Aalborg dates back to 1885:\nAalborg Cricket Klub 1885-1899 (the predecessor of Aab)\nAab Cricket 1899-1989\nAalborg Chang Cricket 1912-2000\nAalborg Cricket Club, 2000-\n\nHenrik Mortensen, Aab, is considered the best and most well-known cricket player in Aalborg history.\n\nFor Chang, Troels Nielsen was the biggest name. Casper Strandvig, Per Pedersen & Jan Anker Nielsen, along with Troels Nielsen, were on the Chang team that brought the championship to the city in the eighties. Aalborg CCs best placement is 4th in the Elite Division and has won the cup once.',
    aboutText: 'Since 2013, Aalborg Cricket Club has been located at the new grounds at Dyrskuepladsen. Participation in the 2nd Division North has been a great success, with many cricket victories for the club, including fielding two teams. In 2015, the club had the opportunity to compete in the 1st Division, a challenge they chose to accept. One reason was to provide more challenge for the active players from Aalborg. In 2015, the club also decided to field only one active team under DCF. The squad and board mainly consist of new players as well as players from the Chang era. The club has enjoyed the help of former players, who have stepped in when the club could not field a team. Aalborg is the second most winning city in Denmark throughout history, with 17 Senior Danish Championships: Aab with 16 titles & Chang with 1.',
    newsTitle: 'Latest News',
    newsDesc: 'Stay updated with the latest happenings at our club',
    upcomingMatchesTitle: 'Upcoming Matches',
    upcomingMatchesLoading: 'Loading upcoming matches...',
    upcomingMatchesEmpty: 'No upcoming matches.',
    schoolCricketTitle: 'School Cricket',
    schoolCricketCard1Title: 'School Cricket in Denmark',
    schoolCricketCard2Title: 'Association Festival',
    schoolCricketVisit: 'Visit Website',
    dateLabel: 'Date',
    timeLabel: 'Time',
    locationLabel: 'Location',
    eventsTitle: 'Upcoming Events',
    eventsDesc: 'Join us for exciting cricket events and activities',
    contactTitle: 'Get in Touch',
    contactDesc: "Have questions? We'd love to hear from you!",
    contactInfo: 'Contact Information',
    followUs: 'Follow Us',
    adminPortal: 'Admin Portal',
    accessAdmin: 'Access Admin Portal',
    getInTouch: 'Get in Touch',
    becomeMember: 'Become a Member',
    membershipBenefit: 'All new members and beginners receive 6 months of free membership. This requires that you have not previously played in DCF tournaments for Danish clubs.',
    membershipFees: 'Annual rates in DKK ♦ Seniors 2000 DKK ♦ Juniors 1000 DKK ♦ Boys 750 DKK ♦ Miniput / Lilleput 500 DKK ♦ Passive members 150 DKK',
    activeMemberInfo: 'You are an active member of ACC when you participate in the club\'s matches under DCF and/or train regularly at the club\'s facilities (outdoor or indoor), or have another membership agreement with the club\'s board.',
    contactFormTitle: 'Contact Us',
    contactFormName: 'Full Name',
    contactFormPhone: 'Phone Number',
    contactFormMessage: 'Message',
    contactFormSubmit: 'Send Message',
    contactFormSuccess: 'Thank you! Your message has been sent successfully.',
    contactFormError: 'An error occurred. Please try again.',
    excellence: 'Excellence',
    excellenceDesc: 'Committed to developing skills and achieving success on and off the field.',
    community: 'Community',
    communityDesc: 'Building lasting relationships and fostering a supportive environment.',
    achievement: 'Achievement',
    achievementDesc: 'Celebrating victories and recognizing the dedication of our members.',
    addressBoxes: [
      {
        icon: '🏏',
        heading: 'Ground',
        address: 'Dyrskueplads, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskueplads,+9200+Aalborg+SV,+Aalborg%2B/data=!4m5!4m4!1m0!1m2!1m1!1s0x464933a17f39d5a3:0x91351939e1b4eef0?sa=X&ved=2ahUKEwjPof6x9IPdAhXGJlAKHfT4CHQQ9RcwC3oECAoQEA',
      },
      {
        icon: '🅿️',
        heading: 'Parking',
        address: 'Hobrovej 437, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir/Hobrovej+437,+9200+Aalborg//@57.0066659,9.8791338,16z/data=!4m8!4m7!1m5!1m1!1s0x464933a2396ee279:0x17f161795534b053!2m2!1d9.8835219!2d57.006666!1m0',
      },
      {
        icon: '📬',
        heading: 'Post Address',
        address: 'H. C. Andersens Vej 20, 9000 Aalborg',
        link: null,
      },
      {
        icon: '🚻',
        heading: 'Changing Room & Cafeteria',
        address: 'Dyrskuevej 2, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskuevej+2,+9200+Aalborg/@57.0065879,9.8825229,16z/data=!4m8!4m7!1m0!1m5!1m1!1s0x464933a1976f7c2d:0xea5304c1daa65d8a!2m2!1d9.886911!2d57.006588',
      },
    ],
    phone: '📞 +45 22 86 20 48',
    email: '✉️ info@aalborg-cricket.dk',
    copyright: '© 2026 Aalborg Cricket Club. All rights reserved.',
    about: 'About',
    news: 'News',
    matches: 'Matches',
    events: 'Events',
    contact: 'Contact',
    light: '☀️ Light',
    dark: '🌙 Dark',
    lang: 'Dansk',
    boardTitle: 'Board',
    boardDescription: "ACC's statutes from the founding general meeting in 2000. Note! Voting rights at the general meeting – only paying members. The financial year follows the calendar year. Statutes for Aalborg Cricket Club.",  },
    statutesText: 'Read statutes',
  da: {
    clubName: 'Aalborg Cricket Klub',
    welcome: 'Velkommen til Aalborg Cricket Klub',
    aboutTitle: 'Om Klubben',
    aboutHistoryTitle: 'Crickethistorie i Aalborg',
    aboutHistoryText: 'Cricket i Danmark har en lang historie. Mest vindende gennem tiden er Svanholm CC, som ligger i Brøndby. Aalborg er nr. 2 by på mesterskabslisten. 17 Senior DM guld er det blevet til gennem tiderne. Aab med 16 DM guld & Chang 1 DM guld.\n\nDet officielle klubcricket i Aalborg går tilbage til 1885:\nAalborg Cricket Klub 1885-1899 (forgængeren for Aab)\nAab Cricket 1899-1989\nAalborg Chang Cricket 1912-2000\nAalborg Cricket Club, 2000-\n\nHenrik Mortensen, Aab må tilskrives pladsen som bedste og mest kendte Cricket spiller gennem tiderne i Aalborg.\n\nFor Chang var Troels Nielsen det største navn. Casper Strandvig, Per Pedersen & Jan Anker Nielsen var ligesom Troels Nielsen på det Chang hold der tog mesterskabet til byen i firserne. Aalborg CC har bedste placering som nr. 4 i Elitedivisionen og en gang vundet pokalen.',
    aboutText: 'Siden 2013 har Aalborg Cricket Club befundet sig i det nye arealer på Dyrskuepladsen. Deltagelsen i 2. Division Nord har været et stor succes og med mange cricket sejr til klubben, hvor man blandt andet stillede med 2 hold. I 2015 fik klubben mulighed for at prøve kræfter med hold i 1. Division og den mulighed valgte klubben at tage. En af grunde var, at der skulle være lidt mere udfordring for de aktive spiller fra Aalborg. Man valgte ligeledes i 2015 at stille med kun 1 aktivt hold under DCF. Truppen og bestyrelsen består mest af nye spiller samt spiller fra Chang tiden. Klubben har haft fornøjelsen af tidligere spiller, som har hjulpet i tilfælde af klubben ikke kunne stille hold. Aalborg er 2. mest vindende by i Danmark gennem tiderne. 17 Senior DM guld er det blevet til. Aab 16 mesterskaber & Chang 1.',
    newsTitle: 'Seneste Nyt',
    newsDesc: 'Hold dig opdateret med de seneste begivenheder i klubben',
    upcomingMatchesTitle: 'Kommende Kampe',
    upcomingMatchesLoading: 'Indlæser kommende kampe...',
    upcomingMatchesEmpty: 'Ingen kommende kampe.',
    schoolCricketTitle: 'Skole Cricket',
    schoolCricketCard1Title: 'Spil cricket i skolen',
    schoolCricketCard2Title: 'Foreningsfestival',
    schoolCricketVisit: 'Besøg Hjemmeside',
    dateLabel: 'Dato',
    timeLabel: 'Tid',
    locationLabel: 'Sted',
    eventsTitle: 'Kommende Begivenheder',
    eventsDesc: 'Deltag i spændende cricketarrangementer og aktiviteter',
    contactTitle: 'Kontakt Os',
    contactDesc: 'Har du spørgsmål? Vi hører gerne fra dig!',
    contactInfo: 'Kontaktinformation',
    followUs: 'Følg Os',
    adminPortal: 'Admin Portal',
    accessAdmin: 'Gå til Admin Portal',
    getInTouch: 'Kontakt',
    becomeMember: 'Bliv Medlem',
    membershipBenefit: 'Alle nye medlemmer og nybegyndere får et 1/2 års gratis kontingent. Dette forudsætter at man ikke tidligere har spillet i DCF turneringer for danske klubber.',
    membershipFees: 'Årlige satser i kr ♦ Seniorer 2000 kr ♦ Junior 1000 kr ♦ Drenge 750 kr ♦ Miniput / Lilleput 500 kr ♦ Passive medlemmer 150 kr',
    activeMemberInfo: 'Man er aktivt medlem i ACC når man deltager i klubbens kampe under DCF og/eller træner regelmæssigt på klubbens anlæg(udendørs eller indendørs), eller har anden aftale om medlemskab med klubbens bestyrelse.',
    contactFormTitle: 'Kontakt Os',
    contactFormName: 'Fuldt navn',
    contactFormPhone: 'Telefonnummer',
    contactFormMessage: 'Besked',
    contactFormSubmit: 'Send Besked',
    contactFormSuccess: 'Takk! Din besked er blevet sendt.',
    contactFormError: 'Der opstod en fejl. Prøv igen.',
    excellence: 'Fremragende',
    excellenceDesc: 'Vi arbejder målrettet på at udvikle færdigheder og opnå succes både på og udenfor banen.',
    community: 'Fællesskab',
    communityDesc: 'Vi bygger varige relationer og skaber et støttende miljø.',
    achievement: 'Præstation',
    achievementDesc: 'Vi fejrer sejre og anerkender medlemmernes engagement.',
    addressBoxes: [
      {
        icon: '🏏',
        heading: 'Bane',
        address: 'Dyrskueplads, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskueplads,+9200+Aalborg+SV,+Aalborg%2B/data=!4m5!4m4!1m0!1m2!1m1!1s0x464933a17f39d5a3:0x91351939e1b4eef0?sa=X&ved=2ahUKEwjPof6x9IPdAhXGJlAKHfT4CHQQ9RcwC3oECAoQEA',
      },
      {
        icon: '🅿️',
        heading: 'Parkering',
        address: 'Hobrovej 437, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir/Hobrovej+437,+9200+Aalborg//@57.0066659,9.8791338,16z/data=!4m8!4m7!1m5!1m1!1s0x464933a2396ee279:0x17f161795534b053!2m2!1d9.8835219!2d57.006666!1m0',
      },
      {
        icon: '📬',
        heading: 'Postadresse',
        address: 'H. C. Andersens Vej 20, 9000 Aalborg',
        link: null,
      },
      {
        icon: '🚻',
        heading: 'Omklædning & Cafeteria',
        address: 'Dyrskuevej 2, 9200 Aalborg SV',
        link: 'https://www.google.dk/maps/dir//Dyrskuevej+2,+9200+Aalborg/@57.0065879,9.8825229,16z/data=!4m8!4m7!1m0!1m5!1m1!1s0x464933a1976f7c2d:0xea5304c1daa65d8a!2m2!1d9.886911!2d57.006588',
      },
    ],
    phone: '📞 +45 22 86 20 48',
    email: '✉️ info@aalborg-cricket.dk',
    copyright: '© 2026 Aalborg Cricket Klub. Alle rettigheder forbeholdes.',
    about: 'Om',
    news: 'Nyt',
    matches: 'Kampe',
    events: 'Begivenheder',
    contact: 'Kontakt',
    light: '☀️ Lys',
    dark: '🌙 Mørk',
    lang: 'English',
    boardTitle: 'Bestyrelse',
    boardDescription: 'ACC´s vedtægter fra den stiftende generalforsamling år 2000 ACC Vedtægter. Bemærk! stemmeret generalforsamling – kun betalende medlemmer. Regnskabet følger kalenderåret.',
    statutesText: 'Læs vedtægter',
  },
};

export default translations;
